"""create pre visit summaries table

Revision ID: 17c99b1b9585
Revises: b675547f188f
Create Date: 2026-08-20 19:39:07.714915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c99b1b9585'
down_revision: Union[str, Sequence[str], None] = 'b675547f188f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_visit_summaries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pre_visit_information_id', sa.BigInteger(), nullable=False),
    sa.Column('urgency_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='urgencylevel'), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=False),
    sa.Column('suggested_questions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pre_visit_information_id'], ['pre_visit_information.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pre_visit_information_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pre_visit_summaries')
    # ### end Alembic commands ###
