"""add doctor leave status

Revision ID: b2d6955b98a0
Revises: b39812986c83
Create Date: 2026-08-24 16:11:00.094935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2d6955b98a0'
down_revision: Union[str, Sequence[str], None] = 'b39812986c83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_leave', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_leave', 'status')
    # ### end Alembic commands ###
