"""add integrity constraints and indexes

Revision ID: b39812986c83
Revises: 2015ed765e9b
Create Date: 2026-08-20 22:20:07.706024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b39812986c83'
down_revision: Union[str, Sequence[str], None] = '2015ed765e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_appointments_doctor_date', 'appointments', ['doctor_id', 'appointment_date'], unique=False)
    op.create_index('ix_appointments_patient_date', 'appointments', ['patient_id', 'appointment_date'], unique=False)
    op.create_check_constraint('ck_appointment_time_range', 'appointments', 'start_time < end_time')
    op.create_index('ix_doctor_leave_doctor_dates', 'doctor_leave', ['doctor_id', 'start_date', 'end_date'], unique=False)
    op.create_check_constraint('ck_doctor_leave_date_range', 'doctor_leave', 'start_date <= end_date')
    op.create_index('ix_doctor_working_hours_doctor_day', 'doctor_working_hours', ['doctor_id', 'day_of_week'], unique=False)
    op.create_check_constraint('ck_prescription_item_duration', 'prescription_items', 'duration_days > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_prescription_item_duration', 'prescription_items', type_='check')
    op.drop_index('ix_doctor_working_hours_doctor_day', table_name='doctor_working_hours')
    op.drop_constraint('ck_doctor_leave_date_range', 'doctor_leave', type_='check')
    op.drop_index('ix_doctor_leave_doctor_dates', table_name='doctor_leave')
    op.drop_constraint('ck_appointment_time_range', 'appointments', type_='check')
    op.drop_index('ix_appointments_patient_date', table_name='appointments')
    op.drop_index('ix_appointments_doctor_date', table_name='appointments')
    # ### end Alembic commands ###
